### ISSUE TITLE
стиль и hover для полей ввода:

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#10]
1)Состояние по умолчанию:
  border: 1px solid #e5e5e5;
  background: #f5f5f5;

2)hover
сейчас при наведении рамка убирается, а она должна оставаться такой же как и в первом состоянии. И фон должен чуть-чуть-чуть светлее становиться

3)с состоянием при фокусе все хорошо (когда на поле установлен фокус) - все хорошо

**Comment by SilentImp** [comment]
Поправил, это касается инпутов только? Не select?
Если да, то проверьте и закройте.

**Comment by karapetyan** [comment]
select тоже это касается

**Comment by karapetyan** [comment]
сейчас у выпадающих списков старое оформление и выглядят они не ок

**Comment by SilentImp** [comment]
Поправил. Проверь, пожалуйста.

**Comment by karapetyan** [comment]
Еще пара моментов:
1) В результате правок сломались стили выпадающих списков:
http://prntscr.com/8o3hdk

2)Цвет шрифта для инпутов и селектов надо сделать темнее:
http://prntscr.com/8o3jfq

**Comment by SilentImp** [comment]
проверь и закрой
