### ISSUE TITLE
выпадающий список с поиском

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#12]
отличается от макета

http://prntscr.com/8n8o5u
http://prntscr.com/8n8oem

а сейчас форма появляется вверх и текущее выбранное значение никак не отделено от элементов списка и сливается с ними. 

можно сделать как в макете изначально предполагалось?

**Comment by SilentImp** [comment]
1. форма открывается вверх или вниз в зависимости от того где хватит места. У меня, например, форма открывается вниз. Я не могу это изменить.

![Скриншот](https://dl.dropboxusercontent.com/u/20810772/PNG/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-10-05%20%D0%B2%2017.14.01.png)
1. не очень понял вторую проблему. Вроде бы поведение совпадает с макетом:
   ![Макет](https://dl.dropboxusercontent.com/u/20810772/PNG/Menu/1%20%D0%9C%D0%B5%D0%BD%D1%8E%20%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F%20-%20%D0%B4%D0%B5%D1%81%D0%BA%D1%82%D0%BE%D0%BF.png)

**Comment by karapetyan** [comment]
на твоих скриншотах, ровно как и на тех, что были в описании issue - все в порядке.

однако здесь проблема хорошо видна:
http://prntscr.com/8o09z4

**Comment by SilentImp** [comment]
Понял о чем речь. 
Смотри, я думаю это можно поправить, только поясни как именно, как разделить список и текущее значение. 
Заставить меню выпадать строго снизу я не могу, да это и плохая идея — это обеспечивает для пользователя возможность видеть выпадашку даже тогда, когда она снизу не поместится.

**Comment by SilentImp** [comment]
жду информацию по разделителю

**Comment by karapetyan** [comment]
сходу сказать не могу, самый простой вариант, как мне кажется, добавить solid border 1px сверху  синего цвета (такого же как и остальная рамка)

что б получился прямоугольник

**Comment by SilentImp** [comment]
Проверь и закрой
