### ISSUE TITLE
позиция заголовка 

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#14]
текущую задачу надо делать после того, как сделаешь эту https://github.com/SilentImp/3waytalk-landing/issues/5

http://prntscr.com/8n8siq

**Comment by karapetyan** [comment]
не сделано

**Comment by SilentImp** [comment]
я и неписал, что сделано, и пуша по этому issue нет :)

**Comment by SilentImp** [comment]
проверь и закрой

**Comment by SilentImp** [comment]
Поднял не 20px.
Проверь все ли ок.
