### ISSUE TITLE
Ресайз картинок

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#15]
1)http://prntscr.com/8n8x6f

2)
http://prntscr.com/8n8v1m
ну и куча остальных сладов

итд, там много их

**Comment by karapetyan** [comment]
не сделано

**Comment by SilentImp** [comment]
не сделано. когда будет — я отпишусь в тредике и тут будет указание на коммит, в котором правки

**Comment by SilentImp** [comment]
проверь и закрой

**Comment by karapetyan** [comment]
- отсутствует картинка
  http://prntscr.com/8qdl62

**Comment by karapetyan** [comment]
- http://prntscr.com/8qdm3f

**Comment by karapetyan** [comment]
- http://prntscr.com/8qdmgn

**Comment by karapetyan** [comment]
- http://prntscr.com/8qdmsn

**Comment by karapetyan** [comment]
- http://prntscr.com/8qdncw

**Comment by SilentImp** [comment]
Проверь и закрой

**Comment by karapetyan** [comment]
Барыню решили оставить как есть, но на больших разрешениях текст
We connect you to a professional interpreter in seconds
No contracts to sign. Live interpreters on demand.
Не должен залезать ей на голову

Плюс из-за последних правок главная сломалась:
http://prntscr.com/8qr7z9

**Comment by SilentImp** [comment]
Посмотри и проверь
