### ISSUE TITLE
изменился текст в заголовке

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#16]
http://prntscr.com/8n8vi4

**Comment by SilentImp** [comment]
Надо изменить на какой?

**Comment by karapetyan** [comment]
на тот который скриншоте
Download 3waytalk today and receive $5 credit!

**Comment by SilentImp** [comment]
проверь и закрой

**Comment by SilentImp** [comment]
поправил текст для десктопа

**Comment by SilentImp** [comment]
жду комментариев по изменению текста. 
пока скрыл его.

**Comment by karapetyan** [comment]
там где помещается пишем
Download 3waytalk today and receive $5 credit!

там где не помещается
Get it now!
