### ISSUE TITLE
Алерт о поддерживаемых брузерах должен быть только в десктопной версии

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#2]
А сейчас он и на мобильной и на таблетке
![image](https://cloud.githubusercontent.com/assets/1526786/10262431/c23313c2-69cf-11e5-85a3-acff6a17aace.png)

**Comment by karapetyan** [comment]
И лого залез под кнопку

**Comment by SilentImp** [comment]
Проверьте и закройте.
