### ISSUE TITLE
поднять заголовок (что б все что под ним тоже поднялось выше) на 30px вверх

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#20]
я не думаю, что именно так следует сделать в коде, но я прикрепляю скрин, что б было понятно какой элемент поднимать

http://prntscr.com/8o0ij8

**Comment by karapetyan** [comment]
и еще:
http://prntscr.com/8o0kqu

**Comment by karapetyan** [comment]
и еще уменьшим margin 
http://prntscr.com/8o0l0g

**Comment by SilentImp** [comment]
проверь и закрой
