### ISSUE TITLE
убираем подчеркивания

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#3]
http://prntscr.com/8n8trf
http://prntscr.com/8n8u2g
http://prntscr.com/8n8ub4

**Comment by karapetyan** [comment]
хотя в этом случае можно вообще без подчеркивания

**Comment by SilentImp** [comment]
а что с реакцией на ховер?
она есть?

**Comment by karapetyan** [comment]
Ага, а что можем сделать? Немного менять цвет ссылки?

**Comment by SilentImp** [comment]
Добавлять подчеркивание при наведении, менять цвет.

**Comment by karapetyan** [comment]
Подчёркивание добавлять не надо, думаю можно слегка менять цвет ссылки

**Comment by SilentImp** [comment]
Проверьте и закройте.
