### ISSUE TITLE
Картинки 2x

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#31]
1) нужно найти фотографию в 2 раза больше 
![аватар](https://dl.dropboxusercontent.com/u/20810772/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-10-22%20%D0%B2%2014.30.57.png)
то есть в разрешении 400x400

**Comment by SilentImp** [comment]
Фотографию
![аватар](https://dl.dropboxusercontent.com/u/20810772/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-10-22%20%D0%B2%2014.30.57.png)
в разрешении 400x400

**Comment by karapetyan** [comment]
http://prntscr.com/8u0o95

**Comment by SilentImp** [comment]
@karapetyan нет, эти не надо. уже даже добавил. 1 слайд — все ок, ничего не надо.

**Comment by SilentImp** [comment]
2. слайд — средний аватар (девушка), указанный выше.
3. слайд — телефон андроид и ios с нажатой и не нажатой кнопкой, так что бы они только состояние кнопки и отличались, в остальном совпадали до пикселя, волны в svg, девушка та же что и н а 2 слайде.
4. слайд — телефон самсунг в объекте не 2х
5. слайд — все ок
6. слайд — все ок
