### ISSUE TITLE
Сломался слайд

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#32]
http://prntscr.com/8tuprb

все стало больше и по вертикали 3-й пункт перестал помещаться на странице

**Comment by SilentImp** [comment]
Проверь

**Comment by karapetyan** [comment]
http://prntscr.com/8udj7c
это проблемно чинить?

**Comment by SilentImp** [comment]
Нет, уменьшил. 
Проверь.

**Comment by karapetyan** [comment]
вроде ок теперь
