### ISSUE TITLE
Изменяем текст(описание) в слайде Conference call

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#34]
было:
Once you’ve connected to an interpreter, you can dial any number or you can select a contact from your phonebook to conference into the call.Calls are connected using VoIP at rates comparable to or lower than major internet phone service providers

стало:

Once you’ve connected to an interpreter, you can dial any number or you can select a contact from your phonebook to conference into the call.

**Comment by SilentImp** [comment]
Проверь и закрой
