### ISSUE TITLE
favico с поддержкой retina, если так можно

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#35]

**Comment by karapetyan** [comment]
насколько я понимаю, дизайнер для этогоне нужен, раз у тебя лого в svg?

**Comment by SilentImp** [comment]
1. пока вообще никакого нет. Предоставите хоть какой то? Логотип который на сайте для favicon не подходит. 
2. в плане формата — нужно icon, png, svg http://caniuse.com/#search=favicon

**Comment by karapetyan** [comment]
генерить будем тут:
http://www.favicomatic.com/

**Comment by SilentImp** [comment]
Проверь и закрой

**Comment by karapetyan** [comment]
ок
