### ISSUE TITLE
Анимации. Первый слайд

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#36]
I) Первый слайд. Анимации описаны в порядке появления

0) Анимация не видна, при первой загрузке страницы. Видимо она проигрывается в фоне, пока крутится спиннер ожидания (синий).

1)Заголовок We connect you to a professional interpreter in seconds 
должен появляться одновременно с
-  подзаголовком No contracts to sign. Live interpreters on demand. 
- барышней на фоне

2) А кнопки Google Play / Appstore должны появляться одновременно с телефонами

3)Блок are you an interpreter должен появляться целиком после появления телефонов

4)После чего появляется Scroll to learn more

**Comment by SilentImp** [comment]
Проверь и закрой

**Comment by SilentImp** [comment]
Проверь и закрой
