### ISSUE TITLE
Анимации. Второй слайд 

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#37]
Порядок появления анимации

0)Появляется заголовок: Call anywhere in the world with your interpreter on the line
1)Jim woods (фото, имя, должность) - одновременно
2)Cheng Sun (фото, имя, должность) одновременно
3)Christina Adams (фото, имя, должность - одновременно
4)Идет линия от Jim'a к Cheng'у и появляются baloon'ы
5)Появляется надпись
Calls are connected using 3G/LTE/WiFi networks with long distance rates similar to or lower than major internet phone service providers

**Comment by SilentImp** [comment]
Проверь и закрой

**Comment by karapetyan** [comment]
1)Заголовок появился
-- увеличить тайм-аут до появления европейца. Сейчас он появляется сразу с заголовком
2) После европейца появляется китаец, а не девушка
3) после китайца появляется девушка
4)полоска должна идти быстрее
5)надпись внизу появляется самой последней

**Comment by SilentImp** [comment]
Cнова проверь

**Comment by karapetyan** [comment]
полоска должна начинать появляться уже после того как девушка появилась полностью. А сейчас она появляется в процессе проигрывания анимации появления девушки.

**Comment by karapetyan** [comment]
прошу прощения и еще одна правка сразу, пускай европеец и азиат появляются одновременно.
Слишком много движений сейчас, глаза разбегаются

**Comment by SilentImp** [comment]
Проверь

**Comment by karapetyan** [comment]
чуть-чуть увеличить тайм-аут появления девушки.

**Comment by SilentImp** [comment]
Проверь

**Comment by karapetyan** [comment]
блин, слишком долго девушка теперь появляется. Хуй с ним, откатывай как было и давай дальше
