### ISSUE TITLE
Анимации. Третий слайд

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#38]
порядок появления элементов
1)шаг 
- Заголовок: Bring an interpreter with you
- подзаголовок: Need an interpreter on the go? Connect to 3waytalk, put your phone in speaker mode and your interpreter will be as if she were standing next to you
- телефон с выключенным динамиком и без девушки 

2)Появляется девушка 

3)Включается динамик (меняется состояние на белое)

4) начинают идти волны

**Comment by SilentImp** [comment]
Проверь и закрой

**Comment by karapetyan** [comment]
порядок верный, но слишком быстро. Такое ощущение, что при переходе на слайд телефон и заголовок уже отобразились. Хотя скорость загрузки в прошлой версии была ок.

надо больше паузы между анимациями сделать. Не успеваешь ничего понять

**Comment by SilentImp** [comment]
Cнова проверь

**Comment by karapetyan** [comment]
отлично
