### ISSUE TITLE
Анимации. Четвертый слайд

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#39]
Порядок появления элементов:
1)
- заголовок 
- подзаголовок
- телефон (сразу с тетенькой)

2)появляется your contact

**Comment by SilentImp** [comment]
Проверь и закрой

**Comment by karapetyan** [comment]
в общем девушка должна появляться после того как телефон появился окончательно
а после того как появилась девушка (анимация завершилась) должен появиться азиат (но с этим вроде ок)

**Comment by SilentImp** [comment]
Проверь

**Comment by karapetyan** [comment]
ок
