### ISSUE TITLE
Как выглядит на нексусе (отступы от заголовков)

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#44]
![1](https://cloud.githubusercontent.com/assets/1526786/10679768/63c17ab4-7923-11e5-92e4-cfd5a8838cd5.png)
![2](https://cloud.githubusercontent.com/assets/1526786/10679766/63bf91cc-7923-11e5-90f5-d21963124957.png)
![3](https://cloud.githubusercontent.com/assets/1526786/10679767/63bf8ace-7923-11e5-8f8f-564cfd48e827.png)
![4](https://cloud.githubusercontent.com/assets/1526786/10679769/63c2f768-7923-11e5-83cd-050e4d1d2263.png) - а тут ок все

**Comment by SilentImp** [comment]
Поправил для мобильных всех оступы сверху. 
Больше слайд не центрируется. 
Проверил на эмуляторе, так как нет устройства. 
На эмуляторе ОК.

**Comment by focusshifter** [comment]
Починились слайды с третьего до конца, а второй чуть уехал - https://www.dropbox.com/s/7iv8e7legthr3wg/2015-10-23%2011.25.38.png?dl=0

**Comment by SilentImp** [comment]
@focusshifter 
Проверь пожалуйста второй слайд.

**Comment by focusshifter** [comment]
Good.
