### ISSUE TITLE
iphone 4s думаю, имеет смысл оставить только текст для него, т.к. один фиг ничего не видно

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#45]
http://cs624527.vk.me/v624527316/44560/YxqKEMli8FY.jpg
http://cs624527.vk.me/v624527316/44572/2r3sdSSJPjs.jpg
http://cs624527.vk.me/v624527316/44569/NZnbp1cvInM.jpg
http://cs624527.vk.me/v624527316/4457b/QoDRwsvgKO0.jpg
http://cs624527.vk.me/v624527316/44584/jY3O2Aok6kQ.jpg
http://cs624527.vk.me/v624527316/4454e/17Ol_y_cOE0.jpg

**Comment by karapetyan** [comment]
и вообще надо  определить минимальное разрешение при котором у нас все помещается, а все, что меньше него либо показывать только текст.

Либо показывать обычный сайт без слайдов, что мне кажется, будет крайне затруднительно? Поэтому скорее все-таки text-only

**Comment by SilentImp** [comment]
Проверьте текстовый режим

**Comment by karapetyan** [comment]
http://cs624527.vk.me/v624527316/44676/Oh5E0tWZnoU.jpg

думаю, что текст про 3g/lte при таком размере экрана лучше не показывать

**Comment by SilentImp** [comment]
Проверь и закрой

**Comment by karapetyan** [comment]
попросил проверить, ждем фидбек от владельца 4s
