### ISSUE TITLE
В последней десктопной опере ломаются анимации

### ISSUE THREAD

**Issue by focusshifter** [SilentImp/3waytalk-landing#48]
На 3-4 слайде как появление элементов слайда, так и нажатия на register / login.

**Comment by SilentImp** [comment]
@focusshifter 
А в чем именно баг? Кажется у меня он не воспроизводится.
Opera 32.0
Скринкаст: https://dl.dropboxusercontent.com/u/20810772/opera_animations.mp4

**Comment by SilentImp** [comment]
@focusshifter @karapetyan 
Кажется речь идет о «подтормаживании». 
Я не могу с этим что то сделать.
Закрываем?

**Comment by SilentImp** [comment]
fullpage.js 2.7.4
css3 отключил

**Comment by SilentImp** [comment]
css3 включил обратно

**Comment by SilentImp** [comment]
проблема на стороне оперы
https://github.com/alvarotrigo/fullPage.js/issues/1389
