### ISSUE TITLE
iphone 6 safari азиат сполз вниз

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#49]
![e4adb816a58611794feeb1a334fc51f4981cc166b356948103pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/1526786/10692550/ffd3c660-799a-11e5-936f-01e4199bd717.jpg)

**Comment by SilentImp** [comment]
Проверьте

**Comment by karapetyan** [comment]
Теперь все сжалось 
![image](https://cloud.githubusercontent.com/assets/1526786/10695495/9f3a4240-79ac-11e5-862c-5237fc938baf.png)

**Comment by karapetyan** [comment]
Айфон тоже на грани на первом слайде вышел за нижнюю границу 
![image](https://cloud.githubusercontent.com/assets/1526786/10695562/f22a69f8-79ac-11e5-944f-559bb3428c8b.png)

**Comment by SilentImp** [comment]
Проверь и закрой

**Comment by karapetyan** [comment]
http://prntscr.com/8ugux7
