### ISSUE TITLE
Contcat us

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#50]
Сверстай контент из попапа в текущей версии на отдельной текстовой странице
https://github.com/SilentImp/3waytalk-landing/issues/51

**Comment by SilentImp** [comment]
Проверьте
http://silentimp.github.io/3waytalk-landing/contacts.html

**Comment by karapetyan** [comment]
текст в левой колонке: 
Netvoices Limited, 11 Hope Street, Douglas
Isle of Man, IM1 1AQ, British isles

а в правой колонке:
Email: mail@3waytalk.com
Tel: +44 7463 241852

**Comment by focusshifter** [comment]
https://db.tt/JKi13KE2 двойной скролл в хроме

**Comment by SilentImp** [comment]
Проверьте
