### ISSUE TITLE
Сверстать текстовую страницу

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#51]
![3waytalk-inner](https://cloud.githubusercontent.com/assets/1526786/10693005/ee80761c-799d-11e5-80d4-cf936a522df2.png)

**Comment by SilentImp** [comment]
Проверьте
http://silentimp.github.io/3waytalk-landing/text.html

**Comment by karapetyan** [comment]
нужен футер, как и на лендинге
