### ISSUE TITLE
Смена пароля

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#53]
![reset-2](https://cloud.githubusercontent.com/assets/1526786/10700693/27d74c22-79c8-11e5-9c10-985dcea07b76.png)

при успешной смене пароля произойдет редирект на главную страницу и будет показан информационный алерт сверху, свидетельствующий о том, что пароль успешно изменен.

**Comment by karapetyan** [comment]
и обрати пожалуйста внимание, что сейчас формы, которые ты сделал не работают в iphone / ipad (просто не нажимаются). Это не критично на тех страницах, т.к. там формы работают только с дестопов, но на данной странице - критично.

**Comment by SilentImp** [comment]
http://silentimp.github.io/3waytalk-landing/password.html
Посмотри пожалуйста

**Comment by karapetyan** [comment]
адаптивность
