### ISSUE TITLE
Ломается стрелка на часах

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#7]
т.к. сама по себе картинка часов местами кривая
и синяя полоска, которая анимирована, ложится не ровно на цифреблат

вот исходник:
https://www.dropbox.com/s/shsjahpq80p1own/%D0%A7%D0%B0%D1%81%D1%8B.psb?dl=0

**Comment by SilentImp** [comment]
проверь и закрой

**Comment by karapetyan** [comment]
в момент завершения анимации стрелка перемещается в другое место (правее и выше на 5px примерно)

**Comment by karapetyan** [comment]
стрелка!

**Comment by karapetyan** [comment]
http://prntscr.com/8r4xm5

**Comment by SilentImp** [comment]
нет, и это ошибка рендеринга браузера. 
я никак на это не могу повлиять

**Comment by SilentImp** [comment]
хотя нет, есть идея, как этот баг спрятать

**Comment by SilentImp** [comment]
Проверь и закрой

**Comment by karapetyan** [comment]
вроде больше не воспроизводится
