### ISSUE TITLE
Алерт о неподдерживаемом браузере

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#8]
http://prntscr.com/8n8hyo

**Comment by SilentImp** [comment]
Привожу макет. 

![Макет](https://dl.dropboxusercontent.com/u/20810772/PNG/Menu/1%20%D0%9C%D0%B5%D0%BD%D1%8E%20%D0%BD%D0%B5%D1%81%D0%BE%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%B8%D0%BC%D1%8B%D0%B9%20%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80.png)

**Comment by SilentImp** [comment]
Убрал, естественно.

**Comment by karapetyan** [comment]
ок
