### ISSUE TITLE
Еще про алерт о неподдерживаемых браузерах

### ISSUE THREAD

**Issue by karapetyan** [SilentImp/3waytalk-landing#9]
http://prntscr.com/8n8j1w

**Comment by SilentImp** [comment]
1. Back перекрывается попапом. Сделать «сдвиг» контента — проблематично. Кроме того вам придется опять решать вопрос скрола.
2. алерт закрывается кликом на крестик. проверил.
3. при клике на next открывается попап. если он открыт, то попап «подпрыгивает».

**Comment by karapetyan** [comment]
ок
